modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU 3.0"

[[mods]]
modId = "yuushya"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "pack.png"
displayURL = "${mod_homepage}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''
    ${mod_description}
    '''
#logoFile = ""

[[dependencies.yuushya]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya]]
modId = "architectury"
mandatory = true
versionRange = "[4.4.59,)"
ordering = "AFTER"
side = "BOTH"