modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU 3.0"

[[mods]]
modId = "yuushya"
version = "${version}"
displayName = "Yuushya Townscape"
authors = "Coco, Xiao2 or XiLaiTL, SQwatermark, XieZai"
description = "Adore the life in a busy city?"
logoFile = "pack.png"

[[dependencies.yuushya]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

