package com.yuushya.registries;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.yuushya.Yuushya;
import com.yuushya.block.YuushyaBlockFactory;
import com.yuushya.block.blockstate.YuushyaBlockStates;
import com.yuushya.blockentity.showblock.ShowBlock;
import com.yuushya.blockentity.showblock.ShowBlockEntity;
import com.yuushya.datagen.BlockStateData;
import com.yuushya.datagen.ModelData;
import com.yuushya.datagen.YuushyaDataProvider;
import com.yuushya.item.TemplateBlockItem;
import com.yuushya.item.YuushyaDebugStickItem;
import com.yuushya.item.showblocktool.*;
import com.yuushya.utils.GsonTools;
import com.yuushya.utils.YuushyaLogger;
import com.yuushya.utils.YuushyaUtils;
import dev.architectury.registry.client.rendering.ColorHandlerRegistry;
import dev.architectury.registry.client.rendering.RenderTypeRegistry;
import dev.architectury.registry.registries.RegistrySupplier;
import net.fabricmc.api.Environment;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DebugStickItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Material;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.yuushya.registries.YuushyaRegistryConfig.*;


public class YuushyaRegistries {
    public static final YuushyaDeferredRegister<Block> BLOCKS = new YuushyaDeferredRegister<>(Registry.BLOCK_REGISTRY);
    public static final YuushyaDeferredRegister<Item> ITEMS = new YuushyaDeferredRegister<>(Registry.ITEM_REGISTRY);
    public static final YuushyaDeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = new YuushyaDeferredRegister<>(Registry.BLOCK_ENTITY_TYPE_REGISTRY);

    public static final Map<String,YuushyaRegistryData.Block> BlockALL=new HashMap<>();
    public static final Map<String,YuushyaRegistryData.Block> BlockTemplate=new HashMap<>();
    public static final Map<String,YuushyaRegistryData.Block> BlockOnly=new HashMap<>();
    public static final Map<String,YuushyaRegistryData.Block> BlockRemain=new HashMap<>();

    public static void registerRegistries(){
        for (YuushyaRegistryData.Block block:YuushyaData.block){
            switch (block.classType){
                case "class"->{}
                case "remain"->{BlockRemain.put(block.name, block);}
                case "template"->{BlockTemplate.put(block.name, block);}
                case "block"->{BlockOnly.put(block.name,block);}
                default -> {
                    BlockALL.put(block.name, block);
                    BLOCKS.register(block.name, ()->YuushyaBlockFactory.create(block));
                    ITEMS.register(block.name, ()->new BlockItem(BLOCKS.get(block.name).get(),new Item.Properties().tab(YuushyaCreativeModeTab.toGroup(block.itemGroup))));
                    if(block.autoGenerated.blockstate){
                        YuushyaDataProvider.of(block.name).type(YuushyaDataProvider.DataType.BlockState).add(block);}
                    if (block.autoGenerated.lootTable){
                        YuushyaDataProvider.of(block.name).type(YuushyaDataProvider.DataType.LootTable).add(block);}
                    if (block.autoGenerated.itemModel){
                        YuushyaDataProvider.of(block.name).type(YuushyaDataProvider.DataType.ItemModel).add(block);}

                }
            }
        }
        for (YuushyaRegistryData.Block block:BlockOnly.values()){
            BLOCKS.register(block.name,()->new YuushyaBlockFactory.BlockWithClassType(BlockBehaviour.Properties.of(Material.METAL),1,"block"));
            ITEMS.register(block.name,()->new BlockItem(BLOCKS.get(block.name).get(),new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_EXTRA_BLOCKS)));
            YuushyaDataProvider dataProvider= YuushyaDataProvider.of(block.name);
            dataProvider.type(YuushyaDataProvider.DataType.BlockState).json(()->BlockStateData.genSimpleBlock(BLOCKS.get(block.name).get(),new ResourceLocation(Yuushya.MOD_ID,"block/"+block.name))).save();
            dataProvider.type(YuushyaDataProvider.DataType.BlockModel).add(block);
            dataProvider.type(YuushyaDataProvider.DataType.ItemModel).add(block);
            dataProvider.type(YuushyaDataProvider.DataType.LootTable).add(block);
        }
        for (YuushyaRegistryData.Block templateBlock:BlockTemplate.values()){
            ITEMS.register(templateBlock.name,()->new TemplateBlockItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_EXTRA_BLOCKS),1,templateBlock.name));
            if (templateBlock.autoGenerated!=null&& templateBlock.autoGenerated.itemModel) YuushyaDataProvider.of(templateBlock.name).type(YuushyaDataProvider.DataType.ItemModel).add(templateBlock).save();
            List<String> templateModels=new ArrayList<>();
            if(templateBlock.blockstate.models!=null) templateModels.addAll(BlockStateData.getModelListFromData(templateBlock.blockstate.models)) ;
            if(templateBlock.blockstate.forms!=null) templateBlock.blockstate.forms.forEach((form)->{templateModels.addAll(BlockStateData.getModelListFromData(form));});
            YuushyaLogger.info(templateModels.toString());
            templateModels.forEach(ModelData::setModelTemplate);

            JsonObject templateBlockJson=YuushyaUtils.NormalGSON.toJsonTree(templateBlock,YuushyaRegistryData.Block.class).getAsJsonObject();
            for (YuushyaRegistryData.Block blockOnly:BlockOnly.values()){
                JsonObject blockOnlyJson=YuushyaUtils.NormalGSON.toJsonTree(blockOnly,YuushyaRegistryData.Block.class).getAsJsonObject();
                YuushyaRegistryData.Block block=combineYuushyaDataBlockJson(blockOnlyJson,templateBlockJson);
                registerTemplateProduct(blockOnly.name,templateBlock,templateModels,block,YuushyaBlockFactory.getBlockProperties(block.properties));
            }
            for (YuushyaRegistryData.Block blockRemain:BlockRemain.values()){
                ResourceLocation blockResourceLocation =new ResourceLocation(blockRemain.name);
                if(blockRemain.texture==null||blockRemain.texture.isEmpty()) blockRemain.texture=new ResourceLocation(blockResourceLocation.getNamespace(),"block/"+blockResourceLocation.getPath()).toString();
                JsonObject blockRemainJson=YuushyaUtils.NormalGSON.toJsonTree(blockRemain,YuushyaRegistryData.Block.class).getAsJsonObject();
                YuushyaRegistryData.Block block=combineYuushyaDataBlockJson(blockRemainJson,templateBlockJson);
                BlockBehaviour.Properties properties = BlockBehaviour.Properties.copy(Registry.BLOCK.get(blockResourceLocation));
                registerTemplateProduct(blockResourceLocation.getPath(),templateBlock,templateModels,block,properties);
            }
        }
    }
    private static YuushyaRegistryData.Block combineYuushyaDataBlockJson(JsonObject blockJson,JsonObject templateBlockJson){
        try {
            GsonTools.extendJsonObject(blockJson, GsonTools.ConflictStrategy.PREFER_FIRST_OBJ, templateBlockJson);
        } catch (GsonTools.JsonObjectExtensionConflictException e) {e.printStackTrace();}
        return YuushyaUtils.NormalGSON.fromJson(blockJson,YuushyaRegistryData.Block.class);
    }
    private static void registerTemplateProduct(String name, YuushyaRegistryData.Block templateBlock, List<String> templateModels, YuushyaRegistryData.Block block, BlockBehaviour.Properties properties){
        if(templateBlock.blockstate.models!=null)  block.blockstate.models=templateBlock.blockstate.models.stream().map((s)->s+"_"+name).toList();
        if(templateBlock.blockstate.forms!=null) block.blockstate.forms=templateBlock.blockstate.forms.stream().map((list)->list.stream().map((s)->s+"_"+name).toList()).toList();

        block.name=templateBlock.name+"_"+name;
        BLOCKS.register(block.name, ()->YuushyaBlockFactory.create(block));
        ITEMS.register(block.name,()->new BlockItem(BLOCKS.get(block.name).get(),new Item.Properties()));

        YuushyaDataProvider dataProvider= YuushyaDataProvider.of(block.name);
        YuushyaDataProvider modelDataProvoder= YuushyaDataProvider.of(YuushyaDataProvider.DataType.BlockModel);
        templateModels.forEach((s)->{
            modelDataProvoder.id(new ResourceLocation(s+"_"+name)).setPrefix("models/").json(()->ModelData.genTemplateModel(s,new ResourceLocation(block.texture))).save();
        });
        dataProvider.type(YuushyaDataProvider.DataType.BlockState).add(block).save();
        dataProvider.type(YuushyaDataProvider.DataType.LootTable).add(block).save();
        dataProvider.type(YuushyaDataProvider.DataType.ItemModel).add(block).save();

        BlockALL.put(block.name,block);
    }

    public static void registerAll(){
//        ITEMS.register("get_blockstate_item", () -> new GetBlockStateItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM), 1));
        ITEMS.register("pos_trans_item",()->new PosTransItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("micro_pos_trans_item",()->new MicroPosTransItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("rot_trans_item",()->new RotTransItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("scale_trans_item",()->new ScaleTransItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("slot_trans_item",()->new SlotTransItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("get_showblock_item",()->new GetShowBlockEntityItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("move_transformdata_item",()->new MoveTransformDataItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("debug_stick_item",()->new YuushyaDebugStickItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),4));
        ITEMS.register("get_lit_item",()->new GetLitItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),2));
        ITEMS.register("form_trans_item",()->new GetLitItem(new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM),2));


        BLOCKS.register("test",()->new Block(BlockBehaviour.Properties.of(Material.METAL)));
        ITEMS.register("test",()->new BlockItem(BLOCKS.get("test").get(),new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM)));
        YuushyaDataProvider yuushyaDataProvider= YuushyaDataProvider.of(new ResourceLocation(Yuushya.MOD_ID,"test"));
        yuushyaDataProvider.type(YuushyaDataProvider.DataType.BlockState).json(()->BlockStateData.genSimpleBlock(BLOCKS.get("test").get(),new ResourceLocation(Yuushya.MOD_ID,"block/test"))).save();
        yuushyaDataProvider.type(YuushyaDataProvider.DataType.BlockModel).json(()->ModelData.genSimpleCubeBlockModel(new ResourceLocation(Yuushya.MOD_ID,"block/test"))).save();
        SHOW_BLOCK= BLOCKS.register("showblock",()->new ShowBlock(BlockBehaviour.Properties.of(Material.METAL).noCollission().noOcclusion().strength(4.0f).lightLevel(blockState ->blockState.getValue(YuushyaBlockStates.LIT)),1));
        ITEMS.register("showblock",()->new BlockItem(BLOCKS.get("showblock").get(),new Item.Properties().tab(YuushyaCreativeModeTab.YUUSHYA_ITEM)));
        SHOW_BLOCK_ENTITY= BLOCK_ENTITIES.register("showblockentity",()->BlockEntityType.Builder.of(ShowBlockEntity::new,BLOCKS.get("showblock").get()).build(null));//Util.fetchChoiceType(References.BLOCK_ENTITY,"yuushya:showblockentity")
    }


    public static void registerClient(){
        BlockOnly.values().forEach((block)->{
            RenderTypeRegistry.register(RenderType.cutout(),BLOCKS.get(block.name).get());
        });
        BlockALL.values().forEach((block)->{
            RenderTypeRegistry.register(YuushyaUtils.toRenderType(block.renderType),BLOCKS.get(block.name).get());
            if (block.colorTint!=null&&block.colorTint.colorType!=null&&!block.colorTint.colorType.isEmpty()&& !block.colorTint.colorType.equals("null")){
                ColorHandlerRegistry.registerBlockColors(YuushyaUtils.toBlockColor(block.colorTint.colorType,block.colorTint.colorString),BLOCKS.get(block.name));
            }
        });
    }


    public static RegistrySupplier<Block> SHOW_BLOCK = null;
    public static RegistrySupplier<BlockEntityType<?>> SHOW_BLOCK_ENTITY = null;


}
