package com.yuushya.registries;

import java.util.ArrayList;
import java.util.List;

public class YuushyaRegistryData{
    public List<Block> block = new ArrayList<>();
    public List<Item> item = new ArrayList<>();
    public List<Particle> particle = new ArrayList<>();
    public String version;

    public static class Block{
        public String classType;
        public String renderType;
        public String name;
        public String itemGroup;
        public Properties properties;
        public ColorTint colorTint;
        public BlockState blockstate;
        public AutoGenerated autoGenerated;
        public String texture;
        public static class AutoGenerated{
            public boolean blockstate;
            public boolean lootTable;
        }
        public static class BlockState{
            public String suit;
            public List<String> states;
            public List<String> models;
        }
        public static class Properties {
            public int hardness;
            public int resistance;
            public int lightLevel;
            public float ambientocclusionLightLevel;
            public String sound;
            public String material;
            public boolean isSolid;
            public boolean hasCollision;
            public boolean isDelicate;
            public boolean isHub;
            public String offset;
            public int lines;
        }
        public static class ColorTint{
            public String colorType;
            public String colorString;
        }
    }
    public static class Item{
        public String classType;
        public String name;
        public String itemGroup;
        public Properties properties;
        public static class Properties {
            public int maxCout;
            public int maxDamage;
            public String rarity;
            public String equipment;
            public boolean fireProof;
            public int lines;
            public String createNbt;
            public String cancelNbt;
        }
    }
    public static class Particle{
        public String name;
    }
    
}
