package com.yuushya.registries;

import java.util.ArrayList;
import java.util.List;

public class YuushyaRegistryData{
    public List<Block> block = new ArrayList<>();
    public List<Item> item = new ArrayList<>();
    public List<Particle> particle = new ArrayList<>();
    public String version;

    public static class Block implements Cloneable{
        public String classType="";
        public String renderType="cutout";
        public String name="";
        public String itemGroup="";
        public Properties properties;
        public ColorTint colorTint;
        public BlockState blockstate;
        public AutoGenerated autoGenerated;
        public String texture;

        @Override
        public Block clone() {
            try {
                Block clone = (Block) super.clone();
                return clone;
            } catch (CloneNotSupportedException e) {
                throw new AssertionError();
            }
        }

        public static class AutoGenerated{
            public boolean blockstate=false;
            public boolean lootTable=false;
        }
        public static class BlockState{
            public String suit="";
            public List<List<String>> forms;
            public List<String> states;
            public List<String> models;
        }
        public static class Properties {
            public int hardness=2;
            public int resistance=2;
            public int lightLevel=0;
            public float ambientocclusionLightLevel=1.0F;
            public String sound;
            public String material="iron";
            public boolean isSolid=false;
            public boolean hasCollision=true;
            public boolean isDelicate=false;
            public boolean isHub;
            public String offset="none";
            public int lines=1;
        }
        public static class ColorTint{
            public String colorType="null";
            public String colorString;
        }
    }
    public static class Item{
        public String classType="";
        public String name="";
        public String itemGroup="";
        public Properties properties;
        public static class Properties {
            public int maxCout=64;
            public int maxDamage=0;
            public String rarity="";
            public String equipment;
            public boolean fireProof=false;
            public int lines=1;
            public String createNbt;
            public String cancelNbt;
        }
    }
    public static class Particle{
        public String name;
    }
    
}
