modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${mod_licence}"

[[mods]]
modId = "yuushya"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "pack.png"
displayURL = "${mod_homepage}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''
    ${mod_description}
    '''

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

#[[mixins]]
#config = "yuushya.mixins.json"
#
#[[mixins]]
#config = "yuushya-common.mixins.json"